---
title: "R Final Test"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

## class: BB105
## name: _______

```{r}
#(1) 請讀取final資料夾下的lvr_prices_big5.RData檔案 [5分]
load("~/R/riii/final/lvr_prices_big5.RData")
load("~/R/riii/final/lvr_prices.RData")  # 我用Linux的R

```

```{r}
#(2) 請問可使用哪個函式觀看檔案的資料結構？[5分]
str(lvr_prices)

```

```{r}
#(3) 請問可使用哪個函式觀看資料前10筆資料？[5分]
lvr_prices[1:10,]

```

```{r}
#(4) 請篩選出
#  1. city_land_type為住宅用
#  2. total_price > 0
#  3. building_sqmeter > 0
#  4. finish_ymd 非空值
#  的房屋資料,並存入house變數中。[8分]

# lvr_prices %>% summarise(n())               # 總共102054筆
# str(lvr_prices) can't retrieve null, so transform factor to Date
lvr_prices$trading_ymd = as.Date(lvr_prices$trading_ymd)
lvr_prices$finish_ymd = as.Date(lvr_prices$finish_ymd)
# sum(is.na(lvr_prices$finish_ymd))           # 21992筆遺失值

library(dplyr)
house = select(lvr_prices, everything()) %>% 
  filter(lvr_prices$city_land_type == '住', lvr_prices$total_price > 0, lvr_prices$building_sqmeter > 0, complete.cases(lvr_prices$finish_ymd))

# nrow(house)                                 # 48374筆
```

```{r}
#(5) 請使用house資料，利用房屋價格(total_price)及房屋平方米數(building_sqmeter)兩欄位，
#    產生一新欄位為每平方米價格(price_per_sqmeter)，並將其四捨五入到整數位。[5分]

house <- select(house, everything()) %>% 
  mutate(price_per_sqmeter = round(total_price / building_sqmeter, digits=0))

head(house)
# nrow(house)                               # 48374筆
```

```{r}
#(6) 請使用house資料，利用scale() 將每平方米價格(price_per_sqmeter)欄位資料標準化
#    ，並剔除掉outlier資料(z-score > 3)。[5分]

house = house[abs(scale(house$price_per_sqmeter)) <= 3,]

# nrow(house)                               # 48336筆
# head(sort(house$price_per_sqmeter, decreasing = T))
# tail(sort(house$price_per_sqmeter, decreasing = T))
```

```{r}
#(7) 請問在house資料中各行政區(area)的資料筆數為何? 可否畫出其長條圖? [5分]
table(house$area)
library('ggplot2')
g <- ggplot(house,aes(x=area, fill=area))
g + geom_bar(stat = 'count') + ylab('筆數') + ggtitle('House') + theme(text=element_text(size=8))

```

```{r}
#(8) 請使用house資料，計算各行政區每平方米價格(price_per_sqmeter)欄位資料的平均數，中位數及標準差 [8分]
house %>%
  group_by(area) %>%
  summarise(AVG=mean(price_per_sqmeter),Median=median(price_per_sqmeter), SD = sd(price_per_sqmeter)) %>%
  arrange(desc(AVG))

```

```{r}
#(9) 請使用house資料,利用ggplot2的facet_wrap函數繪製各行政區房屋每平方米價格(price_per_sqmeter)的直方圖 [8分]
# tail(sort(house$price_per_sqmeter, decreasing = T))
# filter(house, price_per_sqmeter == 0)  checking deviation
summary(house$price_per_sqmeter) # 0 ~ 1092000

g1 <- ggplot(house,aes(x = price_per_sqmeter))
g1 + geom_histogram(binwidth = 10000) + ylab('筆數') + ggtitle('個行政區每坪方尺單價分佈') + facet_wrap(~area) + theme(text=element_text(size=10))

```

```{r}
#(10) 試利用房屋完工日期(finish_ymd)產生一新變數為屋齡(building_age)加入house資料中。
#hint1: 取得當前日期的函數為 Sys.Date()
#hint2: 一年請以365天計算，四捨五入至整數位
#hint3: 將運算完的資料轉為整數型態(integer) [8分]
# unclass(Sys.Date())
# unclass(house$finish_ymd)[1:10]

house = select(house, everything()) %>% 
  mutate(building_age = round((unclass(Sys.Date()) - unclass(house$finish_ymd))/365, digits=0))

str(house$building_age)             # num
as.integer(house$building_age)
# head(house)               check the result
```

```{r}
#(11) 請讀取final資料夾下的house_danger.RData檔案，
#     並將house資料集和house_danger資料集以left outer join方式join起來，
#     存回house變數中 [5分]
load("~/R/riii/final/house_danger.RData")
# str(house$ID)             check column structure and num
# str(house_danger)         check column structure and num

house = merge(x = house, y = house_danger, by = "ID", all.x = TRUE)
# head(house)               check result
```

```{r}
#(12) 請將house資料以8:2的比例分為訓練集和測試集，
#     將訓練集資料存在trainset變數中，
#     將測試集資料存在testset變數中。 [5分]
set.seed(2)
ind<-sample(1:2, size=nrow(house), replace=T, prob=c(0.8, 0.2))

trainset=house[ind==1,]
testset=house[ind==2,]

```

```{r}
#(13) 利用rpart套件建立一預測房屋是否為危樓(danger)的決策樹模型，
#     請利用行政區(area), 屋齡(building_age), 房屋總平方米數(building_sqmeter),
#     房屋類型(building_type)及每平方米價格(price_per_sqmeter)
#     5個變數作為解釋變數放入模型當中建模，並將模型存在house.rp變數中。 [5分]
library('rpart')
con = rpart.control(cp=0.01)
house.rp <- rpart(danger ~ area + building_age + building_sqmeter + building_type + price_per_sqmeter, data = trainset, control = con)

summary(house.rp)
```

```{r}
#(14) 請利用plot()和text()畫出house.rp模型的決策樹 [5分]

par(mfrow=c(1,1))
?plot.rpart
plot(house.rp, uniform=TRUE, branch = 1, margin=0)
text(house.rp, all=TRUE, use.n=TRUE, cex=0.7, family="uming")

table(trainset$building_type)


```
install.packages("showtext")
library(showtext)
showtext_auto(enable = TRUE)
font.add("康熙字典體", "康熙字典體.otf")
```{r}
#(15) 請問此決策數是否需要進行剪枝(prune)？
#     如需剪枝請將修剪後的模型存回house.rp中。 [5分]

printcp(house.rp)
plotcp(house.rp)

```

```{r}
#(16) 請將測試集資料(testset)放入模型中進行驗證，請問此模型的accuracy, precision,
#     recall等績效分別為何？ [5分]

```

```{r}
#(17) 請繪製出此模型的ROC曲線，並計算其AUC。 [8分]

```