# To save & load files
```{R}
save(applenews,file = 'Statistics/applenews.RData')
load('Statistics/applenews.RData')
#table format
write.table(df_name, file = "~/test.txt" , sep = " ")  #csv format
write.csv(test.data, file = "data/test.csv")           
```

# DateTime transform
# Date()表 "日期",  表示距離1970/1/1多少天, 單位為天
# POSIX()表 "時間", 表示距離1970/1/1多少秒, 單位為秒
```{R}
now = Sys.time()         # "2018-02-03 17:32:08 CST"
class(now)               # "POSIXct" "POSIXt" 
unclass(now)             # 1517650329
as.POSIXct(now)          # "2018-02-03 17:32:08 CST"
as.POSIXlt(now)          # 在unclass()後，即可取參數
as.POSIXlt(Sys.time(), "GMT")

Sys.Date()               # "2018-02-03"
as.Date(now)             # "2018-02-03"
class(as.Date(now) )     # "Date"

# 日期相加
as.Date(Sys.time()) + 10 # "2018-02-13"

# 字串轉日期
class(appledaily$dt)     # "character"
as.POSIXct(appledaily$dt,format = '%Y年%m月%d日%H:%M')
```

# 尋找與取代
```{R}
# 法1：注意R的escape word是 \\
sub('\\)','',sub('條件2','取代成',source_name))
# 法2：使用stringr套件的str_match()
library(stringr)
str_match(appledaily$clicked,"人氣\\((\\d+)\\)")[1,2]
```

### 其他常見字串處理函式
```{R}
test_str = c('abcd','bcd','cde')

grep('ab',test_str)             # 尋找字串，回index
grepl('ab',test_str)            # 尋找字串，回boolean
test_str[grep('ab',test_str)]   # return value of index
test_str[grepl('ab',test_str)]  # return value of index

strsplit('abc-def','-')         # 字串分割
nchar(test_str)                 # 字串長度
substring('abcd',2,3)           # 裁剪字串
```


# Manipulate missing data
```{R}
is.na(applenews)                # 回傳boolean null=true
complete.cases(applenews)       # 回傳boolean 與上相反

# 移除missing value
rm.data <- applenews[complete.cases(applenews), ]
# 平均值
mean = as.integer(mean(applenews$clicked,na.rm=T))
# 類別平均值
cat_means = tapply(applenews$clicked,applenews$category,function(e){as.integer(mean(e,na.rm=T))})
# 遺失值補平均值
applenews[is.na(applenews)] = mean_clicked
# 遺失值類別平均值
for(i in 1:length(names(cat_means))){
  applenews[applenews$category == names(cat_means)[i] & is.na(applenews$clicked),'clicked'] = cat_means[i]
}
```


### package dplyr
- 類SQL語法,select,filter,arrange,mutate...
- Chaining %>%, debug方便
- install.packages('dplyr')

##### cheat sheet
- https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

#資料篩選 (select)
```{R}
library(dplyr)
# select
applenews[, c("category","clicked")]      # traditional
select(applenews,category,clicked)        # choose two col
select(applenews,category:clicked)        # from col_B ~ col_C
select(applenews,contains('click'))       # col_name contains xxx

# where
applenews[applenews$category == "娛樂",][1:3,]      # traditional
filter(applenews, category == "娛樂")[1:3,]         # dplyr

# and (&) /or (|)
head(filter(applenews, category == "娛樂" & clicked > 1000))

# in
filter(applenews, category %in% c("娛樂", "社會"))[1:3,]

# 同時 select 和 where(filter)
filter(select(applenews,title:clicked),category == '娛樂')[1:3,]

# order by (arrange)
select(applenews,title:clicked) %>% 
  filter(category == "社會") %>% 
  arrange(.,desc(clicked)) %>%
  head()

# aggregate calculate (sum(), mean(), count(), etc)
select(applenews,clicked) %>% 
    count()

# 使用mutate產生新欄位
select(applenews, title, category, clicked) %>% 
  mutate(portion = clicked/sum(applenews$clicked) *100) %>%
  arrange(desc(portion)) %>%
  head()
```

# Summarise的應用
```{R}
name1 <- c("Bob","Mary","Jane","Kim")
weight <- c(60,65,45,55)
height <- c(170,165,140,135)
weta <- 1:4
df1 <- data.frame(name1,weight,height,weta)

summarise(df1,avg_weight=mean(weight),avg_height=mean(height)) # 個別指定
summarise_all(df1[-1],mean)                     # 所有col都計算
summarise_if(df1,is.numeric,mean)               # int的col做計算
summarise_at(df1,vars(weight,height,weta),mean) # 配合vars函数
summarise_at(df1,vars(weight:weta),mean)    # from col_a to col_c
summarise_at(df1,vars(contains("eig")),mean)    # 包含某字串
summarise_at(df1,vars(matches(".t.")),mean)     # reg_ex
summarise_at(df1,vars(starts_with("w")),mean)   # col start from
summarise_at(df1,vars(ends_with("ht")),mean)    # col end with
summarise_at(df1[,-1],vars(everything()),mean)  # all col
applenews %>% summarise(n())                    #一般計數
applenews %>% summarise(n_distinct(category))   #不重複計數

# group_by & summarise
applenews %>%
  group_by(category) %>%
  summarise(clicked_sum = sum(clicked, na.rm=TRUE)) %>%
  arrange(desc(clicked_sum))

applenews %>%
  group_by(category) %>% 
  summarise_at(.vars=vars(clicked,portion),.funs=funs(sum))

applenews %>%
  group_by(category) %>% 
  summarise_at(.vars=vars(clicked),.funs=funs(sum,mean))

applenews %>%
  group_by(category) %>%
  summarise_at(.funs=funs(min,max), .vars=vars(matches('clicked')), na.rm=T)
```





---
title: "R_basic3"
author: "York Lin"
date: "2018年01月30日"
output: html_document
---
### anscombe dataset
- https://zh.wikipedia.org/wiki/%E5%AE%89%E6%96%AF%E5%BA%93%E5%A7%86%E5%9B%9B%E9%87%8D%E5%A5%8F

### 統計圖
```{R}
setwd("~/lecture/riii")
load("Statistics/cdc.Rdata")
cdc$exerany = as.factor(cdc$exerany)
cdc$hlthplan = as.factor(cdc$hlthplan)
cdc$smoke100 = as.factor(cdc$smoke100)

#屬貭資料: 長條圖、圓餅圖
barplot(table(cdc$smoke100))
?barplot
barplot(table(cdc$smoke100),xlab='有無吸菸',ylab='人數',main='title',col='blue',family="Songti SC")

pie(table(cdc$smoke100))
pie(table(cdc$genhlth))
pie(table(cdc$genhlth),col = rainbow(5))

#加上各分類比例
pct = round(table(cdc$genhlth) / length(cdc$genhlth) *100,1)
labels = paste(names(pct),pct,"%")
pie(table(cdc$genhlth), labels = labels)


gender_smokers = table(cdc$gender,cdc$smoke100)

mosaicplot(gender_smokers)

#屬量資料: 直方圖、盒鬚圖、莖葉圖
hist(cdc$age)

par(mfrow=c(3,1))
hist(cdc$height)
hist(cdc$height,breaks = 30)
hist(cdc$height,breaks = 50)

stem(cdc$age)
tmp=sample(cdc$age,100)
stem(sample(cdc$age,100))
?stem
stem(sample(cdc$age,100),scale=2)

par(mfrow=c(1,1))
boxplot(cdc$weight)
boxplot(cdc$weight, horizontal=TRUE)
boxplot(cdc$weight ~ cdc$gender)
boxplot(cdc$height ~ cdc$gender)

bmi = (cdc$weight/cdc$height^2) * 703
boxplot(bmi ~ cdc$genhlth)

#觀察兩組資料間關係:點散布圖
plot(cdc$weight, cdc$height)
plot(cdc$weight, cdc$wtdesire)


png(filename='test123.png')
plot(cdc$weight, cdc$height)
dev.off()

```


### package:ggplot2
##### documentation
- http://docs.ggplot2.org/current/

##### cheat sheet
- https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf

##### why ggplot2?
- fancy by default, good for demo and report 
- consistent across all kinds of plot in syntax and behavior
- strong support community(the mostly download package on CRAN)
```{R}
#basic syntax
#ggplot(data,aes(x,y,group,...))+geom_object(...)
#install.packages('ggplot2')
library('ggplot2')

g <- ggplot(cdc,aes(x=height,y=weight))
g+geom_point(aes(col=exerany))

g <- ggplot(cdc,aes(x=genhlth))
g+geom_bar()
g+geom_bar() + ylab('Count') + ggtitle('cdc')
#fill => 填滿顏色; color => 邊線顏色
g+geom_bar(fill='snow',color='black')

g <- ggplot(cdc,aes(x=genhlth,fill=gender))
g+geom_bar()
#g <- ggplot(cdc,aes(x=genhlth))
#g+geom_bar(aes(fill=gender))

g_bygrp <- ggplot(cdc,aes(x=exerany,fill=genhlth))
g_bygrp + geom_bar()
g_bygrp + geom_bar(position='stack')
g_bygrp + geom_bar(position='dodge')
g_bygrp + geom_bar(position='identity')

precounted = as.data.frame(table(cdc$genhlth,dnn = c('genhlth')))
precounted
ggplot(precounted,aes(x=genhlth,y=Freq))+ geom_bar(stat='identity')

g <- ggplot(cdc,aes(x=genhlth,y=height))
g + geom_boxplot()

#facet
g <- ggplot(cdc,aes(x=weight))
g2 = g+ geom_histogram()+facet_wrap(~genhlth)
g2

ggsave(filename='your_file_name.png',plot = g2)
```

# 資料預處理

### 把dt轉換成日期型態
```{R}
#getwd()
setwd('~/lecture/riii')

# 以as.POSIXct()轉換
load('Statistics/appledaily.RData')
str(appledaily)
head(appledaily$dt)
dt = as.POSIXct(appledaily$dt,format = '%Y年%m月%d日%H:%M')
appledaily$dt = dt
head(appledaily$dt)

# Date 和 POSIX 差別
# Date類別表示 "日期",  表示距離1970/1/1多少天, 單位為天
# POSIX類別表示 "時間", 表示距離1970/1/1多少秒, 單位為秒

now = Sys.time()
class(now)
unclass(now)

nowDate = as.Date(now)
class(nowDate)
unclass(nowDate)

#比較as.POSIXct() 和 as.POSIXlt
t1 = as.POSIXct(appledaily$dt,format = '%Y年%m月%d日%H:%M')
class(t1)
head(unclass(t1))

t2 = as.POSIXlt(appledaily$dt,format = '%Y年%m月%d日%H:%M')
class(t2)
unclass(t2)

#difftime
Sys.time() - appledaily$dt[1]
```

### 擷取點擊數中數值部分
```{R}
#方法一：利用sub函數取代
clicked = sub('\\)','',sub('人氣\\(','',appledaily$clicked))
clicked = as.integer(clicked)
head(clicked)

#方法二：使用stringr套件的str_match()
library(stringr)
?str_match
clicked = as.integer(str_match(appledaily$clicked,"人氣\\((\\d+)\\)")[,2])

appledaily$clicked = clicked
head(clicked)
```

### 其他常見字串處理函式
```{R}
#grep()  ==> return index
test_str = c('abcd','bcd','cde')
grep('a',test_str)
test_str[grep('a',test_str)]

#grepl() ==> return boolean 
grepl('a',test_str)
test_str[grepl('a',test_str)]

#strsplit() ==> 字串分割
splited = strsplit('abc-def','-')
splited
class(splited)
unlist(splited)

#substring() ==> 取得部份字串
test_s = 'abcdef'
nchar(test_s)
substring(test_s,2,nchar('abcdef')-1)
```

### 替換類別名稱
```{R}
names(table(appledaily$category))
appledaily$category[appledaily$category == "國際\",\"LA\",\"SF\",\"NY\",\"US"] = '國際'
appledaily$category[appledaily$category == "國際\",\"SF\",\"US"] = '國際'
names(table(appledaily$category))
```

### 儲存處理過的檔案
```{R}
applenews = appledaily
save(applenews,file = 'Statistics/applenews.RData')
```

### 遺失值處理(missing value)
```{R}
applenews = appledaily
na_list = sample(1:nrow(applenews),30)
applenews[na_list,'clicked'] = NA

#找尋遺失值
is.na(applenews)
sum(is.na(applenews$clicked))

#移除missing value
complete.cases(applenews)
rm.data <- applenews[complete.cases(applenews), ]
str(rm.data)

#以全體平均填補
applenews = appledaily
na_list = sample(1:nrow(applenews),30)
applenews[na_list,'clicked'] = NA

mean_clicked = as.integer(mean(applenews$clicked,na.rm=T))
applenews$clicked[is.na(applenews$clicked)] = mean_clicked

sum(is.na(applenews$clicked))

#以類別平均填補
applenews = appledaily
na_list = sample(1:nrow(applenews),30)
applenews[na_list,'clicked'] = NA

cat_means = tapply(applenews$clicked,applenews$category,function(e){as.integer(mean(e,na.rm=T))})
cat_means

for(i in 1:length(names(cat_means))){
  applenews[applenews$category == names(cat_means)[i] & is.na(applenews$clicked),'clicked'] = cat_means[i]
}

sum(is.na(applenews$clicked))
```

### package dplyr
- 類SQL語法,select,filter,arrange,mutate...
- Chaining %>%, debug方便

##### cheat sheet
- https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

```{R}
load('Statistics/applenews.RData')
str(applenews)

applenews = applenews[,-1]

#install.packages('dplyr')
library(dplyr)

#原先R 提供的過濾功能
head(applenews[applenews$category == "娛樂",])

#dplyr 的過濾功能
head(filter(applenews, category == "娛樂"))

#and/or 
head(filter(applenews, category == "娛樂" & clicked > 1000))
head(filter(applenews, category == "娛樂" | clicked > 1000))

#篩選多個類別
head(filter(applenews, category %in% c("娛樂", "社會")))

#原先R的欄位選取
head(applenews[, c("category","clicked")])

#dplyr 的欄位選取

#選擇列舉出的欄位
head(select(applenews,category,clicked))
#選擇從category~clicked欄位
head(select(applenews,category:clicked))
#選擇欄位名稱含有click字串的欄位
head(select(applenews,contains('click')))

?matches

#想同時filter 和 select
head(filter(select(applenews,category:clicked),category == '娛樂'))

#使用Chaining
select(applenews,category:clicked) %>%
  filter(category == '娛樂') %>%
  head()

applenews %>% 
  select(category:clicked) %>%
  filter(category == '娛樂') %>%
  head()

#使用Arrange將資料做排序
applenews %>%
  select(category,clicked) %>% 
  filter(category == "社會") %>% 
  arrange(.,desc(clicked)) %>%
  head()

# 總點擊數
freqsum = applenews %>%
  select(clicked) %>% 
  sum()

#使用mutate產生新欄位
applenews %>%
  select(title, category,clicked) %>% 
  mutate(portion= clicked / freqsum) %>%
  arrange(desc(portion)) %>%
  head()

#新增portion欄位
applenews = applenews %>%
  mutate(portion= clicked / freqsum)

#group_by & summarise
applenews %>%
  group_by(category) %>%
  summarise(clicked_sum = sum(clicked, na.rm=TRUE)) %>%
  arrange(desc(clicked_sum))

#多個欄位計算
applenews %>%
  group_by(category) %>% 
  summarise_at(.vars=vars(clicked,portion),.funs=funs(sum))

applenews %>%
  group_by(category) %>% 
  summarise_at(.vars=vars(clicked),.funs=funs(sum,mean))

applenews %>%
  group_by(category) %>%
  summarise_at(.funs=funs(min,max), .vars=vars(matches('clicked')), na.rm=T)

#一般計數
applenews %>%
  summarise(n())

#不重複計數
applenews %>%
  summarise(n_distinct(category))

cat_stat = applenews %>%
  group_by(category) %>%
  summarise(clicked_sum = sum(clicked)) 

cat_stat
#繪製長條圖
barplot(cat_stat$clicked_sum, names.arg=cat_stat$category, col=rainbow(length(cat_stat$category)),family="Songti SC")
#繪製圓餅圖
pie(cat_stat$clicked_sum, label = cat_stat$category,family="Songti SC")
```

### 補充：連接資料庫範例(以sqlite3為例)
```{R}
# sqlite3 download page: https://www.sqlite.org/download.html
#install.packages('dbplyr')
#install.packages('RSQLite')
library('dbplyr')
library('RSQLite')

my_database = src_sqlite('./mydatabase',create=T)
copy_to(my_database,applenews,temporary = F)
tbl(my_database,"applenews")
tbl(my_database,"applenews") %>% collect()

category_stat = tbl(my_database,"applenews") %>% 
  group_by(category) %>%
  summarise_at(.funs=funs(min,max,mean), .vars=vars(matches('clicked'))) %>%
  arrange(desc(mean)) %>%
  collect()

library('ggplot2')
g <- ggplot(category_stat,aes(x=category,y=mean))
g + geom_bar(stat='identity') + theme(text=element_text(size=16,  family="Songti SC")) + scale_x_discrete(limits=category_stat$category)
```